Repository FRONTENDBOOTCAMP-13th/Final-07-Chillin-Code, pull requests merged in 2025-07, with the labels that each got.

#2 ✨ Feat: PR 테스트 resolve #01
  src/app/favicon.ico
Labels: Feature, Done, Frontend

#10 Feature/footer/juno
  public/fonts/variable/Human-BeomseokNeoVF.ttf
  public/fonts/variable/Human-BeomseokNeoVF.woff
  public/fonts/variable/Human-BeomseokNeoVF.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/components/layout/footer.tsx
  src/styles/components/Footer.module.css
  src/styles/globals.css
Labels: 🔵 P3-Normal, 🛠 Feature, 🎨 UI/UX, 👀 Needs Review

#14 🐳 chore: modern reset 파일 추가
  src/styles/reset/modern-reset.css
Labels: 📝 Docs

#18 ✨ Feat: 모바일 header UI 구현
  src/app/layout.tsx
  src/components/layout/header.tsx
  src/styles/components/header.module.css
  src/styles/globals.css
Labels: 🛠 Feature

#20 ✨ feat: Web Header UI 구현
  src/app/layout.tsx
  src/components/layout/header.tsx
  src/styles/components/header.module.css
Labels: 🛠 Feature

#29 ✨ feat: Header 반응형 UI 구현
  public/icons/white-menu-icon.svg
  src/components/layout/header.tsx
  src/styles/components/header.module.css
Labels: 🛠 Feature

#31 ✨ feat : myPage mobile header UI 구현
  public/icons/mine-shopping-cart-icon.svg
  src/app/layout.tsx
  src/components/layout/header.tsx
  src/components/layout/myPageMobileHeader.tsx
  src/styles/components/myPageMobileHeader.module.css
Labels: 🛠 Feature

#32 ♻️ refactor : mypage Header UI 수정
  public/icons/close-icon.svg
  src/components/layout/myPageMobileHeader.tsx
  src/styles/components/myPageMobileHeader.module.css
Labels: ♻️ Refactor

#40 ✨ feat : 우편번호찾기 페이지 UI 구현
  src/app/layout.tsx
  src/app/zip-code/page.tsx
  src/styles/zip-code/zip-code.module.css
Labels: 🛠 Feature

#43 ♻️ refactor : my-page Header 아이콘 경로 수정
  src/components/layout/myPageMobileHeader.tsx
Labels: 🛠 Feature

#46 ♻️ refactor : my page Header Icon 경로 수정
  src/components/layout/myPageHeader.tsx
Labels: ♻️ Refactor

#47 ✨ feat : stamp toast UI 구현
  public/images/stamp-images/toastUI/confetti.svg
  src/app/stamp/page.tsx
  src/styles/stamp/stamp.module.css
Labels: 🛠 Feature

#48 🍱 assets : rename icon
  public/icons/arrow-icon.svg
  public/icons/back-icon.svg
  public/icons/calendar-icon.svg
  public/icons/cart-icon.svg
  public/icons/cart-white-icon.svg
  public/icons/chat-icon.svg
  public/icons/check-icon.svg
  public/icons/circle-arrow-close-icon.svg
  public/icons/circle-close-icon.svg
  public/icons/empty-heart-icon.svg
  public/icons/eye-icon.svg
  public/icons/filter-icon.svg
  public/icons/heart-filled-icon.svg
  public/icons/home-icon.svg
  public/icons/home-white-icon.svg
  public/icons/info-icon.svg
  public/icons/link-icon.svg
  public/icons/menu-icon.svg
  public/icons/minus-icon.svg
  public/icons/mypage-icon.svg
  public/icons/mypage-white-icon.svg
  public/icons/plus-icon.svg
  public/icons/recent-icon.svg
  public/icons/recent-white-icon.svg
  public/icons/refresh-icon.svg
  public/icons/search-icon.svg
  public/icons/stamp-icon.svg
  public/icons/stamp-white-icon.svg
  public/icons/start-icon.svg
  public/icons/닫기 아이콘.svg
  public/logo/sophie-logo.svg
Labels: 🖼️ Assets

#49 ♻️ refactor : mobile zip-code page 아이콘 경로 수정
  src/app/zip-code/page.tsx
  src/components/layout/header.tsx
Labels: ♻️ Refactor

#51 ✨ feat : checkBox 컴포넌트 제작
  src/components/common/check-box.tsx
  src/styles/components/check-box.module.css
Labels: 🛠 Feature

#64 ♻️ refactor :mobile header UI gap 수정
  src/styles/components/header.module.css
Labels: ♻️ Refactor

#84 [Page] 모바일 최근 본 상품 페이지
  public/images/mainPage/diary-decor-event.svg
  public/images/mainPage/fabric-collection-event.svg
  public/images/mainPage/howls-hero.svg
  public/images/mainPage/kiki-hero.svg
  public/images/mainPage/paper-theater-event.svg
  public/images/mainPage/shopie-warehouse-event-bg.svg
  public/images/mainPage/shopie-warehouse-hero.gif
  public/images/mainPage/shopie-warehouse-hero.svg
  public/images/mainPage/totoro-hero.svg
  public/images/products/howl/howl-bottle.svg
  public/images/products/howl/howl-candle-light.svg
  public/images/products/howl/howl-coster.svg
  public/images/products/howl/howl-diorama.svg
  public/images/products/howl/howl-frying-pan.svg
  public/images/products/howl/howl-sholder-bag.svg
  public/images/products/howl/howl-stained-glass-jewelry-box.svg
  public/images/products/howl/howl-sun-catcher.svg
  public/images/products/kiki/kiki-4set-dish.svg
  public/images/products/kiki/kiki-4set-multi-case.svg
  public/images/products/kiki/kiki-diary-sticker.svg
  public/images/products/kiki/kiki-handkerchief.svg
  public/images/products/kiki/kiki-magnet.svg
  public/images/products/kiki/kiki-mascort-keyring.svg
  public/images/products/kiki/kiki-round-bento-box.svg
  public/images/products/kiki/kiki-wodden-chopsticks.svg
  public/images/products/totoro/totoro-chair-cushion.svg
  public/images/products/totoro/totoro-holder.svg
  public/images/products/totoro/totoro-magnet.svg
  public/images/products/totoro/totoro-mini-figure.svg
  public/images/products/totoro/totoro-socks.svg
  public/images/products/totoro/totoro-stamp.svg
  public/images/products/totoro/totoro-towel.svg
  public/images/products/totoro/totoro-water-aperture.svg
  src/components/layout/footerNavBar.tsx
  src/pages/mainPage.tsx
  src/pages/mobileRecentProductPage.module.css
  src/pages/mobileRecentProductPage.tsx
Labels: 🛠 Feature

#91 ✨ feat : 모바일 뷰 회원탈퇴 UI 구현
  src/app/layout.tsx
  src/app/myPage/accountDelete/page.tsx
  src/styles/myPage/accountDelete/accountDelete.module.css
Labels: 🛠 Feature

#92 ✨ Feat: 버튼 컴포넌트 추가
  src/components/common/button.tsx
  src/styles/components/button.module.css
Labels: 🛠 Feature

#95 ✨ Feat: 모바일 카테고리 페이지 구현
  src/components/layout/header.tsx
  src/pages/category.module.css
  src/pages/category.tsx
Labels: 🛠 Feature

#98 ✨ feat : web 마케팅 수신동의 UI 구현
  src/app/layout.tsx
  src/app/myPage/marketingAgreement/page.tsx
  src/styles/myPage/marketingAgreement/marketingAgreement.module.css
Labels: 🛠 Feature

#99 ♻️ refactor : 마케팅 수신동의 UI 간격 수정
  src/styles/myPage/marketingAgreement/marketingAgreement.module.css
Labels: 🛠 Feature

#103 ✨ Feat: 웹 카테고리 페이지 구현
  src/pages/mobileCategory.module.css
  src/pages/mobileCategory.tsx
  src/pages/webCategory.module.css
  src/pages/webCategory.tsx
Labels: 🛠 Feature

#111 ♻️ Refactor: 메인 페이지 컴포넌트화
  src/app/mainPage/page.tsx
  src/app/mainPage/sections/eventSection.tsx
  src/app/mainPage/sections/productSection.tsx
  src/app/mainPage/sections/reviewSection.tsx
  src/app/page.tsx
  src/pages/mainPage.module.css
  src/pages/mainPage.tsx
  src/styles/mainPage/mainPage.module.css
  src/styles/mainPage/sections/eventSection.module.css
  src/styles/mainPage/sections/productSection.module.css
  src/styles/mainPage/sections/reviewSection.module.css
  src/types/Index.ts
Labels: ✨ Enhancement

#114 🐳chore : DB 초기 데이터 추가
  api/dbinit/team/data.js
  api/dbinit/team/uploadFiles/4549743942247_600_01.jpg
  api/dbinit/team/uploadFiles/4970381518875_500_1.jpg
  api/dbinit/team/uploadFiles/4970381700690_600.jpg
  api/dbinit/team/uploadFiles/4970381700737_600.jpg
  api/dbinit/team/uploadFiles/4973307631443_500_1.jpg
  api/dbinit/team/uploadFiles/4973307658631_600_01.jpg
  api/dbinit/team/uploadFiles/4977524193753_600.jpg
  api/dbinit/team/uploadFiles/4990593468362_600_01.jpg
  api/dbinit/team/uploadFiles/4990593476626_600_02.jpg
  api/dbinit/team/uploadFiles/4990593478095_600_02.jpg
  api/dbinit/team/uploadFiles/4990593499212_600.jpg
  api/dbinit/team/uploadFiles/4990593500888_600_02.jpg
  api/dbinit/team/uploadFiles/4990593500895_600_02.jpg
  api/dbinit/team/uploadFiles/4992272795745_600.jpg
  api/dbinit/team/uploadFiles/4992272886061_600.jpg
  api/dbinit/team/uploadFiles/4992272920376_600.jpg
  api/dbinit/team/uploadFiles/4992272943610_600.jpg
  api/dbinit/team/uploadFiles/4992272943627_600.jpg
Labels: 📝 Docs

#119 ♻️ refactor : layout 파일 console.log 삭제
  src/app/layout.tsx
Labels: ♻️ Refactor

#121 ♻️ refactor : rewards 페이지 UI 간격 수정
  src/app/myPage/rewards/page.tsx
Labels: ♻️ Refactor

#122 ♻️ refactor : rewards 페이지 UI 수정
  src/app/myPage/rewards/page.tsx
  src/styles/myPage/rewards/rewards.module.css
Labels: ♻️ Refactor

#123 ♻️ refactor : header UI Link 연결
  src/components/layout/header.tsx
  src/components/layout/headerHamburgerMenu.tsx
  src/styles/components/header.module.css
  src/styles/components/headerHamburgurMenu.module.css
Labels: ♻️ Refactor

#127 ♻️ Refactor: 메인 페이지 productSection API 연동
  src/app/mainPage/page.tsx
  src/app/mainPage/sections/productSection.tsx
  src/styles/mainPage/sections/productSection.module.css
Labels: ♻️ Refactor

#130 ♻️ refactor : global.css 코드 수정
  src/styles/globals.css
Labels: ♻️ Refactor

#135 ♻️ Refactor: css.module 관련 오류 리펙토링
  api/dbinit/team/data.js
  src/app/categoryPage/mobile/page.tsx
  src/app/categoryPage/mobile/productCard.tsx
  src/app/categoryPage/mobile/productGrid.tsx
  src/app/categoryPage/web/categoryPage.tsx
  src/app/recentPage/mobile/product.tsx
  src/app/types/productType.ts
  src/styles/categoryPage/mobile/categoryHeader.module.css
  src/styles/categoryPage/mobile/categoryPage.module.css
  src/styles/categoryPage/mobile/categoryProductCard.module.css
  src/styles/categoryPage/mobile/categoryProductGrid.module.css
  src/styles/categoryPage/web/categoryPage.module.css
  src/styles/mainPage/mainPage.module.css
  src/styles/mainPage/sections/productSection.module.css
  src/styles/mainPage/sections/reviewSection.module.css
  src/styles/recentPage/mobile/recentProduct.module.css
  src/styles/recentPage/web/recentProduct.module.css
Labels: ♻️ Refactor
