Repository FRONTENDBOOTCAMP-13th/Final-07-Chillin-Code, pull requests merged in 2025-08, with the labels that each got.

#151 ♻️ Refactor: 모바일 카테고리 API 구현 완료
  public/icons/grid-button-icon.svg
  src/app/categoryPage/mobile/categoryClient.tsx
  src/app/categoryPage/mobile/filterModal.tsx
  src/app/categoryPage/mobile/header.tsx
  src/app/categoryPage/mobile/page.tsx
  src/app/categoryPage/mobile/productCard.tsx
  src/app/categoryPage/mobile/productGrid.tsx
  src/app/categoryPage/web/categoryPage.tsx
  src/app/recentPage/mobile/product.tsx
  src/app/recentPage/web/product.tsx
  src/components/layout/footerNavBar.tsx
  src/styles/categoryPage/mobile/categoryFiterModal.module.css
  src/styles/categoryPage/mobile/categoryHeader.module.css
  src/styles/categoryPage/mobile/categoryPage.module.css
  src/styles/categoryPage/mobile/categoryProductCard.module.css
  src/styles/categoryPage/mobile/categoryProductGrid.module.css
  src/styles/globals.css
Labels: ✨ Enhancement, ♻️ Refactor

#154 ♻️ Refactor: 모바일, 웹 최근 본 상품 페이지 API 기능 구현
  src/app/categoryPage/mobile/productCard.tsx
  src/app/categoryPage/web/categoryPage.tsx
  src/app/fetch/product.ts
  src/app/layout.tsx
  src/app/mainPage/sections/productSection.tsx
  src/app/recentPage/mobile/page.tsx
  src/app/recentPage/mobile/product.tsx
  src/app/recentPage/web/page.tsx
  src/app/recentPage/web/product.tsx
  src/app/recentPage/web/recentModal.tsx
  src/components/layout/header.tsx
  src/styles/components/footerNavBar.module.css
  src/styles/recentPage/mobile/recentProduct.module.css
  src/styles/recentPage/web/recentProduct.module.css
  src/utils/recentProduct.ts
  src/zustand/useRecentModal.ts
Labels: ♻️ Refactor

#158 Feature/shopping cart/jinseob
  api/bruno/team/test/bruno.json
  api/bruno/team/test/collection.bru
  api/bruno/team/test/environments/sample.bru
  api/bruno/team/test/게시물 목록 조회.bru
  api/bruno/test/bruno.json
  api/bruno/test/collection.bru
  api/bruno/test/environments/sample.bru
  api/bruno/test/post test.bru
  api/bruno/test/test1.bru
  api/bruno/test/게시물 조희.bru
  api/dbinit/team/data.js
  src/app/mainPage/sections/productSection.tsx
  src/app/shoppingcart/cartItem.tsx
  src/app/shoppingcart/mobileCartView.tsx
  src/app/shoppingcart/page.tsx
  src/app/shoppingcart/summary.tsx
  src/app/shoppingcart/test/page.tsx
  src/app/shoppingcart/webCartView.tsx
  src/app/stamp/StampWebAsideMenu.tsx
  src/app/stamp/StampWebMainContent.tsx
  src/app/stamp/StampWebSideContent.tsx
  src/app/stamp/StampWebSideToast.tsx
  src/app/stamp/StampWebToast.tsx
  src/app/stamp/page.tsx
  src/app/stamp/stamp web file
  src/app/stamp/stampMobileBoard.tsx
  src/app/stamp/stampMobileToast.tsx
  src/app/stamp/stampMobileUserInfo.tsx
  src/app/stamp/stampWebView.tsx
  src/app/test/page.tsx
  src/components/layout/header.tsx
  src/components/layout/myPageHeader.tsx
  src/styles/shoppingCart/shoppingCart.module.css
  src/styles/stamp/stamp.module.css
  src/types/user.ts
  src/zustand/userCartStore.ts
Labels: 🛠 Feature

#160 ♻️ Refactor: 2차 배포를 위한 build 오류 수정
  src/app/categoryPage/mobile/filterModal.tsx
  src/app/categoryPage/mobile/productCard.tsx
  src/app/categoryPage/web/categoryPage.tsx
  src/app/recentPage/mobile/product.tsx
  src/app/recentPage/web/product.tsx
  src/styles/globals.css
  src/styles/mainPage/sections/eventSection.module.css
Labels: ♻️ Refactor

#162 ♻️ refactor : myPageHeader 경로수정
  src/components/layout/myPageHeader.tsx
Labels: ♻️ Refactor

#163 ♻️ refactor : myPageWebAsideMenu 경로 수정
  src/app/myPage/orderDelivery/webAsideMenu.tsx
  src/app/myPage/stamp/StampWebMainContent.tsx
  src/app/myPage/stamp/StampWebSideContent.tsx
  src/app/myPage/stamp/StampWebSideToast.tsx
  src/app/myPage/stamp/StampWebToast.tsx
  src/app/myPage/stamp/page.tsx
  src/app/myPage/stamp/stampMobileBoard.tsx
  src/app/myPage/stamp/stampMobileToast.tsx
  src/app/myPage/stamp/stampMobileUserInfo.tsx
  src/app/myPage/stamp/stampWebView.tsx
  src/app/stamp/StampWebAsideMenu.tsx
  src/app/stamp/stamp web file
Labels: ♻️ Refactor

#164 ♻️ refactor : rewards 페이지 사이드바 수정
  src/app/myPage/rewards/page.tsx
Labels: ♻️ Refactor

#168 ♻️ Refactor: 상세보기페이지 API 구현
  src/app/categoryPage/mobile/productCard.tsx
  src/styles/categoryPage/mobile/categoryProductCard.module.css
Labels: ♻️ Refactor

#171 ✨ feat : 장바구니 기능 구현
  public/images/stampImages/stamp/eighthStamp.svg
  public/images/stampImages/stamp/fifthStamp.svg
  public/images/stampImages/stamp/firstStamp.svg
  public/images/stampImages/stamp/fourthStamp.svg
  public/images/stampImages/stamp/secondStamp.svg
  public/images/stampImages/stamp/seventhStamp.svg
  public/images/stampImages/stamp/sixthStamp.svg
  public/images/stampImages/stamp/thirdStamp.svg
  src/app/(user)/login/loginForm.tsx
  src/app/myPage/stamp/StampWebMainContent.tsx
  src/app/myPage/stamp/StampWebSideContent.tsx
  src/app/myPage/stamp/StampWebSideToast.tsx
  src/app/myPage/stamp/stampMobileBoard.tsx
  src/app/myPage/stamp/stampMobileToast.tsx
  src/app/myPage/stamp/stampWebView.tsx
  src/app/products/[id]/prouctDetailCalc.tsx
  src/app/products/[id]/webDetailContent.tsx
  src/app/shoppingcart/summary.tsx
  src/styles/shoppingCart/shoppingCart.module.css
  src/styles/stamp/stamp.module.css
  src/zustand/userStore.ts
Labels: 🛠 Feature

#172 💄 Style: 모바일 제품 상세 보기 페이지 버튼 추가
  src/app/products/[id]/mobileDetailContent.tsx
  src/app/products/[id]/prouctDetailCalc.tsx
  src/styles/detailPage/detailPage.module.css
Labels: 🎨 UI/UX, ♻️ Refactor

#175 ♻️ refactor : 모바일 장바구니 기능 추가 구현
  src/app/products/[id]/mobileDetailContent.tsx
  src/app/products/[id]/prouctDetailCalc.tsx
Labels: 🛠 Feature, ♻️ Refactor

#179 refactor/stampCount/jinseob
  src/app/myPage/stamp/StampWebMainContent.tsx
  src/app/myPage/stamp/stampMobileBoard.tsx
  src/app/myPage/stamp/stampMobileUserInfo.tsx
  src/app/order/mobileTotalPrice.tsx
  src/app/order/webFinalRecipe.tsx
  src/app/order/webPayInfo.tsx
Labels: 🛠 Feature

#189 ♻️ refactor : stamp 오류 수정
  api/dbinit/team/data.js
  src/app/myPage/stamp/StampWebMainContent.tsx
  src/app/myPage/stamp/StampWebSideContent.tsx
  src/app/myPage/stamp/StampWebSideToast.tsx
  src/app/myPage/stamp/StampWebToast.tsx
  src/app/myPage/stamp/stampMobileBoard.tsx
  src/app/myPage/stamp/stampMobileToast.tsx
  src/app/shoppingcart/mobileCartView.tsx
  src/app/shoppingcart/webCartView.tsx
  src/styles/shoppingCart/shoppingCart.module.css
  src/styles/stamp/stamp.module.css
Labels: ♻️ Refactor

#194 ♻️ Refactor: 카테고리 탭 필터 초기화 기능 추가
  src/app/categoryPage/mobile/categoryClient.tsx
  src/app/categoryPage/mobile/page.tsx
  src/app/categoryPage/web/categoryPage.tsx
  src/app/categoryPage/web/page.tsx
  src/components/layout/header.tsx
  src/styles/components/header.module.css
  src/styles/mainPage/sections/productSection.module.css
  src/styles/mainPage/sections/reviewSection.module.css
Labels: ♻️ Refactor

#200 ♻️ refactor : stamp coffeti 크기 수정
  src/styles/stamp/stamp.module.css
Labels: ♻️ Refactor

#204 ♻️ refactor : stampToast 이미지 경로 수정
  src/app/myPage/stamp/StampWebSideToast.tsx
  src/app/myPage/stamp/StampWebToast.tsx
  src/app/myPage/stamp/stampMobileToast.tsx
Labels: ♻️ Refactor

#215 ♻️ refactor : data.json 파일 수정
  api/dbinit/team/data.json
  api/dbinit/team/uploadFiles/1000186532_detail_074.jpg
  api/dbinit/team/uploadFiles/4527837704889_600.jpg
  api/dbinit/team/uploadFiles/47476_1.jpg
  api/dbinit/team/uploadFiles/4970381218416_600.jpg
  api/dbinit/team/uploadFiles/4973307451591_600.jpg
  api/dbinit/team/uploadFiles/4973307658907_600_01.jpg
  api/dbinit/team/uploadFiles/4974475934336_600.jpg
  api/dbinit/team/uploadFiles/4975946017367_600_02.jpg
  api/dbinit/team/uploadFiles/4977524129769_600.jpg
  api/dbinit/team/uploadFiles/4990593428335_02.jpg
  api/dbinit/team/uploadFiles/4990593453481_500_2.jpg
  api/dbinit/team/uploadFiles/4990593464340_600_01.jpg
  api/dbinit/team/uploadFiles/8800286491125_600_01.jpg
  api/dbinit/team/uploadFiles/8809954464065_600_01.jpg
  api/dbinit/team/uploadFiles/9791142303722_600.jpg
  api/dbinit/소피의창고/bruno.json
  api/dbinit/소피의창고/dbinit.bru
  api/dbinit/소피의창고/environments/shopies.bru
  api/dbinit/소피의창고/당첨내역조회.bru
Labels: ♻️ Refactor
